/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SolutionsRouteImport } from './routes/solutions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/company': typeof CompanyRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/company': typeof CompanyRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/company': typeof CompanyRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/company'
    | '/chat'
    | '/contact'
    | '/customers'
    | '/download'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/signup'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/company'
    | '/chat'
    | '/contact'
    | '/customers'
    | '/download'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/signup'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/capabilities'
    | '/company'
    | '/chat'
    | '/contact'
    | '/customers'
    | '/download'
    | '/login'
    | '/platform'
    | '/pricing'
    | '/signup'
    | '/solutions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CompanyRoute: typeof CompanyRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CompanyRoute: CompanyRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
