"""Release verification for DACEXY.

This verifier is intentionally non-invasive: it never imports or executes the
Electron desktop agent. It validates source invariants, Python syntax, the
Alembic migration chain, and the fresh-database upgrade/downgrade path.
"""
from __future__ import annotations

import ast
import hashlib
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
errors: list[str] = []

def get_migration_head() -> str | None:
    versions = {}
    down_revisions = set()
    for migration_file in sorted((ROOT / "backend" / "alembic" / "versions").glob("*.py")):
        text = migration_file.read_text(encoding="utf-8")
        marker = 'revision = "'
        if marker not in text:
            continue
        candidate = text.split(marker, 1)[1].split('"', 1)[0]
        versions[candidate] = migration_file
        down_marker = 'down_revision = "'
        if down_marker in text:
            down_revisions.add(text.split(down_marker, 1)[1].split('"', 1)[0])
    heads = [revision for revision in versions if revision not in down_revisions]
    if len(heads) != 1:
        return None
    return heads[0]

expected_head = get_migration_head()

required = [
    ROOT / "backend/app/main.py",
    ROOT / "backend/app/config.py",
    ROOT / "backend/app/routers/razorpay_router.py",
    ROOT / "backend/app/routers/license_router.py",
    ROOT / "inst2/installer/install.ps1",
    ROOT / "inst2/installer/skills",
]
for p in required:
    if not p.exists():
        errors.append(f"missing: {p.relative_to(ROOT)}")

# Protected desktop agent files: verify exact release hashes, but never modify or execute them.
manifest = ROOT / "DESKTOP_AGENT_UNCHANGED.sha256"
if manifest.exists():
    for line in manifest.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        digest, rel = line.split(maxsplit=1)
        path = ROOT / rel
        if not path.exists():
            errors.append(f"protected desktop source missing: {rel}")
            continue
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != digest:
            errors.append(f"final desktop source hash mismatch: {rel}")
else:
    errors.append("missing desktop immutability manifest")

# Final NSIS package owns the runtime packaging path directly.
nsi = ROOT / "fe/dacexy/desktop/installer.nsi"
if nsi.exists():
    nsi_text = nsi.read_text(encoding="utf-8")
    if 'SetOutPath "$INSTDIR\\inst2\\installer"' not in nsi_text or 'File /r "${INST2DIR}\\installer\\*.*"' not in nsi_text:
        errors.append("NSIS installer does not package inst2/installer explicitly")

skills = list((ROOT / "inst2/installer/skills").rglob("SKILL.md"))
if len(skills) < 630:
    errors.append(f"expected >=630 skills, found {len(skills)}")

# Python syntax without py_compile: this does not create __pycache__ files.
for p in (ROOT / "backend").rglob("*.py"):
    try:
        ast.parse(p.read_text(encoding="utf-8"), filename=str(p))
    except Exception as exc:
        errors.append(f"python syntax error {p.relative_to(ROOT)}: {exc}")

# Final release archives must not contain generated bytecode.
pyc = list(ROOT.rglob("*.pyc"))
if pyc:
    errors.append(f"generated bytecode remains: {len(pyc)} files")

# Migration smoke test: a fresh DB must upgrade to head, downgrade to base,
# and upgrade to head again. This catches broken revision IDs and SQLite-
# incompatible migration operations before packaging.
def run_migration_smoke_test() -> None:
    backend = ROOT / "backend"
    with tempfile.TemporaryDirectory(prefix="dacexy-migration-") as td:
        db_path = Path(td) / "release_verify.db"
        env = os.environ.copy()
        env["JWT_SECRET"] = "release-verification-secret-0123456789-abcdefghijklmnopqrstuvwxyz"
        env["DATABASE_URL"] = f"sqlite:///{db_path.as_posix()}"
        env["PYTHONDONTWRITEBYTECODE"] = "1"
        commands = [
            ["alembic", "upgrade", "head"],
            ["alembic", "downgrade", "base"],
            ["alembic", "upgrade", "head"],
            ["alembic", "current"],
        ]
        for command in commands:
            result = subprocess.run(
                command,
                cwd=backend,
                env=env,
                capture_output=True,
                text=True,
                timeout=120,
            )
            if result.returncode != 0:
                output = (result.stdout + "\n" + result.stderr).strip()
                raise RuntimeError(f"{' '.join(command)} failed: {output[-4000:]}")
        # Verify against the repository's actual migration head rather than a stale hard-coded revision.
        if expected_head is None or f"{expected_head} (head)" not in result.stdout:
            raise RuntimeError(f"unexpected Alembic head output: {result.stdout.strip()}; expected {expected_head} (head)")

try:
    run_migration_smoke_test()
except Exception as exc:
    errors.append(f"Alembic fresh-db smoke test failed: {exc}")

if errors:
    print("RELEASE VERIFY: FAIL")
    print("\n".join(f"- {e}" for e in errors))
    sys.exit(1)

print(f"RELEASE VERIFY: PASS | skills={len(skills)} | backend syntax=ok | migrations={expected_head}(head)")
print("Desktop agent source: release hash-verified")
